POM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('myMap/', include('myMap.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),
    
    path('', views.home, name="home"),
    path('city/<str:pk>/', views.city, name='city'),
    path('add-city/', views.addCity, name='add-city'),
    path('update-city/<str:pk>/', views.updateCity, name='update-city'),
    path('delete-city/<str:pk>/', views.deleteCity, name='delete-city'),

    path('place/<str:pk>/', views.place, name='place'),
    path('add-place/', views.addPlace, name='add-place'),
    path('update-place/<str:pk>/', views.updatePlace, name='update-place'),
    path('delete-place/<str:pk>/', views.deletePlace, name='delete-place'),
    path('add-photo/', views.addPhoto, name='add-photo'),

]

base/models.py
from django.db.models.deletion import CASCADE
from django.db import models
from django.contrib.auth.models import User

class Continente(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class City(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    country = models.CharField(max_length=50, null=True)
    continente = models.ForeignKey(Continente, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name

class Place(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    tag = models.CharField(max_length=50)
    price = models.CharField(max_length=50, null=True)
    rating = models.CharField(max_length=50, null=True)
    # latLong =
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

class Photo(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    image = models.ImageField(null=False, blank=False)
    place = models.ForeignKey(Place, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.name

base/forms.py
from django.forms import ModelForm
from .models import City, Place

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = '__all__'
        exclude = ['user']

class PlaceForm(ModelForm):
    class Meta:
        model = Place
        fields = '__all__'
        exclude = ['user']

base/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.http import HttpResponse
# from datetime import datetime
from .models import City, Continente, Place, Photo
from .forms import CityForm, PlaceForm

def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')
        
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist.')
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username and password does not match.')

    context = {'page':page}
    return render(request, 'base/login_register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('home')

def registerPage(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error occurred during registration.')
            
    return render(request, 'base/login_register.html', {'form':form})

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    cities = City.objects.filter(
        Q(continente__name__icontains=q) |
        Q(name__icontains=q) |
        Q(country__icontains=q)
        )
    continentes = Continente.objects.all()
    city_count = cities.count()
    context = {
        'cities':cities,
        'continentes': continentes
    }
    return render(request, 'base/home.html', context)

def city(request, pk):
    city = City.objects.get(id=pk)
    city_places = city.place_set.all().order_by('-created')
    context = {
        'city':city,
        'places': city_places,
    }
    return render(request, 'base/cityPage.html', context)

@login_required(login_url='login')
def addCity(request):
    form = CityForm()
    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            city = form.save(commit=False)
            city.user = request.user
            return redirect('home')
    context = {'form': form}
    return render(request, 'base/city_form.html', context)

@login_required(login_url='login')
def updateCity(request, pk):
    city = City.objects.get(id=pk)
    form = CityForm(instance=city)
    if request.method == 'POST':
        form = CityForm(request.POST, instance=city)
        if form.is_valid():
            form.save()
            return redirect('home')

    context = {'form': form}
    return render(request, 'base/city_form.html', context)

@login_required(login_url='login')
def deleteCity(request, pk):
    city = City.objects.get(id=pk)
    if request.method == 'POST':
        city.delete()
        return redirect('home')
    return render(request, 'base/delete.html', {'obj':city})

def place(request,pk):
    place = Place.objects.get(id=pk)
    photos = place.photo_set.all()
    context = {'place': place, 'photos': photos}
    return render(request, 'base/placePage.html', context)

@login_required(login_url='login')
def addPlace(request):
    form = PlaceForm()
    if request.method == 'POST':
        form = PlaceForm(request.POST)
        if form.is_valid():
            place = form.save(commit=False)
            place.user = request.user
            return redirect('home')
    context = {'form': form}
    return render(request, 'base/place_form.html', context)

@login_required(login_url='login')
def updatePlace(request, pk):
    place = Place.objects.get(id=pk)
    form = PlaceForm(instance=place)
    if request.method == 'POST':
        form = PlaceForm(request.POST, instance=place)
        if form.is_valid():
            form.save()
            return redirect('home')

    context = {'form': form}
    return render(request, 'base/place_form.html', context)

@login_required(login_url='login')
def deletePlace(request,pk):
    place = Place.objects.get(id=pk)
    if request.user != place.user:
        return HttpResponse('You do not have the right to make this operation')

    if request.method == 'POST':
        place.delete()
        return redirect('home')
    return render(request, 'base/delete.html', {'obj':place})

@login_required(login_url='login')
def addPhoto(request):
    places = Place.objects.all()
    if request.method == 'POST':
        data = request.POST
        image = request.FILES.get('image')
        photo = Photo.objects.create(
            place = Place.objects.get(id=data['place']),
            name = data['name'],
            image=image,
        )
        return redirect('home')

    context = {'places': places}
    return render(request, 'base/addPhoto.html', context)

def viewPhoto(request, pk):
    photo = Photo.objects.get(id=pk)
    context = {'photo': photo}
    return render(request, 'base/photo.html', context)

base/templates/base/addPhoto.html
{% extends 'main.html' %}
{% block content %}

<div>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label>Name</label>
            <input required name="name" type="text">
        </div>

        <div>
            <label>Select A Place</label>
            <select name="place">
                {% for place in places %}
                    <option value="{{place.id}}">{{place.name}}.</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label>Upload images</label>
            <input required name="image" type="file">
        </div>
        <button type="submit">Upload</button>
    </form>

    
</div>

{% endblock %}

base/templates/base/cityPage.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-8 px-5">
            <h1 class="pt-5">{{city.name}}</h1>
            <div class="row">
                {% for place in places %}
                    <div class="col-md-6 py-5">
                        <div class="mh-100" style="width: 400px; height: 200px;">
                            <img src="{% static 'images/3.jpg' %}" class="img-fluid">
                        </div>
                    </div>
                    <div class="col-md-6 py-5">
                        <h2><a href="{% url 'place' place.id %}">{{place.name}}</a></h2>
                        <p>{{place.comment}}</p>
                        <div class="place-price">
                            <p>{{place.rating}}</p>
                            <h4>{{place.price}}</h4>
                        </div>
                        <div class="float-end">
                            <span class="badge text-bg-dark">{{place.tag}}</span>
                        </div>
                        <div>
                            <a href="{% url 'update-place' place.id %}">Edit</a>    
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-2 pl-5">
            <h2>Select Filters</h2>
            <h4>Type</h4>
            {% for place in places %}
            <div class="input-group mb-3">
                <div class="input-group-text">
                    <input class="form-check-input mt-0" type="checkbox" value="">
                    <p>{{place.tag}}</p> <span>(0)</span>
                </div>                       
            </div>
            {% endfor %}
            <h4>Rating</h4>
            {% for place in places %}
            <div class="input-group mb-3">
                <div  class="input-group-text">
                    <input class="form-check-input mt-0" type="checkbox" value=""> 
                    <p>{{place.rating}}</p> <span>(0)</span>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>


</div>
<div class="pagination">
    <img src="{% static 'images/arrow.png' %}">
    <span class="current">1</span>
    <span>2</span>
    <span>3</span>
    <span>&middot; &middot; &middot; &middot;</span>
    <span>10</span>
    <img src="{% static 'images/arrow.png' %}" class="right-arrow">

</div>

{% endblock %}

base/templates/base/city_form.html
{% extends 'main.html' %}
{% block content %}

<div>

    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" />

    </form>
</div>

{% endblock %}

base/templates/base/delete.html
{% extends 'main.html' %}
{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{obj}}"?</p>
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type="submit" value="Confirm" >
</form>

{% endblock %}

base/templates/base/home.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div  class="container ms-auto p-5">
    <div class="text-center">
        <img class="img-fluid" src="{% static 'images/banner.png' %}" alt="">
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-3 pt-5">
            <h5>Browse by Continent</h5>
            <hr>
            <div class="list-group">
                <ul class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <a href="{% url 'home' %}">All</a>
                    </div>
                    <span class="badge bg-primary rounded-pill">{{continente.count}}</span>
                </ul>    
                {% for continente in continentes %}
                <ul class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <a href="{% url 'home' %}?q={{continente.name}}">{{continente.name}}</a>
                    </div>
                    <span class="badge bg-primary rounded-pill">{{continente.city_set.all.count}}</span>
                </ul>
                {% endfor %}
            </div>
        </div>
        <div  class="col-8 pt-2">
            <h2 class="">List of Cities</h2>
            <div class="row">
                {% for city in cities %}
                <div  class="col-md-3 py-5">
                    <img class="img-thumbnail" src="{% static 'images/4.jpg' %}">
                    <span>
                        <h3><a href="{% url 'city' city.id %}">{{city.name}}</a></h3>
                        <p>{{city.continente.name}}</p>
                    </span>
                    <a href="{% url 'update-city' city.id %}">Edit</a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %}

{% block content %}

{% if page == 'login' %}
<div>
    <form method="POST" action="">
        {% csrf_token %}

        <label>Username:</label>
        <input type="text" name="username" placeholder="Enter Username" />
        <label>Password:</label>
        <input type="passoword" name="password" placeholder="Enter Password" />

        <input type="submit" value="Login" />

    </form>
    <p>haven't signed up yet?</p>
    <a href="{% url 'register' %}">Sign up</a>
</div>
{% else %}
<div>
    <form method="POST" action="">
        {% csrf_token %}

        {{form.as_p}}

        <input type="submit" value="Register" />

    </form>
    <p>already signed up yet?</p>
    <a href="{% url 'login' %}">login</a>


</div>

{% endif %}

{% endblock content %}

base/templates/base/photo.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<div>
    <div>
        <img src="{{photo.image.url}}">
        <h3>{{photo.name}}</h3>
    </div>

</div>

{% endblock %}

base/templates/base/placePage.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div>
        <h1>{{place.name}}</h1>
        <p><a href="">{{place.city.name}}</a>, {{place.city.country}}</p>
    </div>
    <div>
        {% for photo in photos %}
        <div  class="mh-100" style="width: 250px; height: 200px;">
            <img src="{{photo.image.url}}" class="img-fluid">
        </div>
        {% empty %}
        <h3>No Photos ...</h3>
        {% endfor %}
    </div>
    <div>
        <h3>Brief Description</h3>
        <p>{{place.comment}}</p>
    </div>
    <div class="map">
        <h3>Location on map</h3>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2970.122888131338!2d12.490042215699862!3d41.890214172634444!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132f61b6532013ad%3A0x28f1c82e908503c4!2sColosseum!5e0!3m2!1sen!2sca!4v1661099865234!5m2!1sen!2sca" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        
    </div>    
</div>

{% endblock %}

base/templates/base/place_form.html
{% extends 'main.html' %}
{% block content %}

<div>

    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" />

    </form>
</div>

{% endblock %}